### ISSUE TITLE
Исчезает меню на странице Статистика

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#110]

**Comment by punkusha** [comment]
[Android Support Library issue 83109] (https://code.google.com/p/android/issues/detail?id=183109)

**Comment by gsbelarus** [comment]
Так может не надо переходить на 23? Пока там ошибки?

**Comment by punkusha** [comment]
Багов меньше, чем в предыдущем.

**Comment by gsbelarus** [comment]
После мержа кода надо перепроверить.
