### ISSUE TITLE
дивиденты не должны попадать в удержания

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#113]

**Comment by YRozmysl** [comment]
Да, это неверное. Дивиденды - это начисления, а не удержания. В удержаниях они могли бы быть, если бы это был такой вид удержания "Дивиденды", что по своей сути означало бы, что человеку их выдали отдельно, например через кассу, или другим способом. Но даже и в этом случае они тоже должны были быть и в начислениях.

**Comment by punkusha** [comment]
Так были сформированы данные в Гедымiне.
