### ISSUE TITLE
Не обновляются даннные в приложении

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/GedeminSalary#120]
Не обновляются данные. Поясню. На базе есть такая ф-ция "Обновить данные". Если, например, человеку среди месяца насчитали оклад
100000 (т.е. расчитали в итоговом), для того, чтобы эта сумма пришла сотруднику на мобильное приложение  мы запустили   "Обновить данные". Обновили в приложении - все замечательно, сумма подтянулось. Проходит время и бухгалтер просто откорректировал этот оклад с 100000 до 2000000. Снова нажали "Обновить данные" но ничего не обновилось в мобильном приложении. Если надо, пример, есть конкретный рабочий пример.

**Comment by punkusha** [comment]
fixed

**Comment by YRozmysl** [comment]
Вопрос не решился, все могу показать и смоделировать на реальных данных на последних настройках
