### ISSUE TITLE
Непонятный экран авторизации

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#123]
На экране видно Имя и Фамилия и доступна кнопка Далее. То, что есть еще поля ввода невидно. При нажатии на кнопку Далее ничего не происходит. На самом деле, выводится сообщение о незаполненном поле, но выводится оно в невидимой части экрана.

Что сделать:

1. Вывести скрол бар или каким-то другим образом показать пользователю, что экран длинный и его можно проматывать вниз.

2. При выводе ошибки (незаполненное поле) проматывать экран, чтобы это поле было видимо пользователю.

**Comment by gsbelarus** [comment]
По прежнему не видно. Скролл бар должен быть всегда виден. Обычные люди будут пользоваться. Не программисты. 

Хотя бы сделать прокрутку на поле, которое не заполнено.

**Comment by sywka** [comment]
Как правило в android приложениях скроллбар показывают во время скролла. Мне кажется достаточно будет фокуса на некорректно заполненное поле.

**Comment by gsbelarus** [comment]
Для начала можно и так.
