### ISSUE TITLE
Календарь на основе БД

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#126]
Календарь в рабочем графике должен браться из БД, а не из гугла. Имеются ввиду выходные, праздничные, рабочие дни.

**Comment by alexandra-gsoftware** [comment]
Универсального календаря в базе данных Гедымина нет. Есть графики, которых может быть много. Есть праздничные дни в отдельной табличке. Т.ч. можно выделять цветом субботу-воскресенье и государственные праздники, если они внесены....

**Comment by gsbelarus** [comment]
Человека, на его мобильном устройстве, будет интересовать имеенно ЕГО РАБОЧИЙ график. Если у нас субботавс выходные, в стране, но именно у этого человека, такой сменный режим, что он работает в конкретную неделю, в сб и вс, то НА ЕГО графике они должны быть показаны как рабочие. 

И гугл тут не причем. В конце концов, если человеку просто захочется посмотреть календарь (не предприятия, а вообще), то он откроет гугл календарь -- приложение бесплатное и есть на каждом андроиде. Дублировать его у себя нет никакого смысла.

**Comment by alexandra-gsoftware** [comment]
Суббота и воскресенье  в календарях выделяются в первую очередь для того, чтобы легче ориентироваться визуально. Например, вы знаете, что не работаете по субботам-воскресеньям, но вам все равно удобнее смотреть в календарь, где они выделены.

Поэтому компромисс: государственные выходные подсвечиваем другим фоном, рабочие дни конкретного человека выделяем шрифтом. Остальное точками, как сейчас.

**Comment by YRozmysl** [comment]
Все замечательно в случае, если не было никаких переносов.

**Comment by alexandra-gsoftware** [comment]
так переносы видны в графике, разве нет?

**Comment by YRozmysl** [comment]
Если берем  календарь рабочий сотрудника из БД, то вопросов нет - там все корректно и адекватно.

**Comment by alexandra-gsoftware** [comment]
ок, варианты
1) оставить как есть (только точки)
2) все точки убрать, выделять цветом рабочие дни из графика. При этом дополнительные события не видны.
3) выделять цветом рабочие дни, но не убирать точки
4) выделять цветом рабочие дни, рисовать какой-нибудь загнутый уголок у дня, если там есть дополнительные события
5) каждое событие выделять своим цветом (если несколько событий в один день, то выбирать одно - главное)
.....
Кто что думает?

**Comment by gsbelarus** [comment]
Ни надо ничего думать. надо сделать правильно и НЕ ПУТАТЬ КАЛЕНДАРЬ С РАБОЧИМ ГРАФИКОМ.

**Comment by gsbelarus** [comment]
Первое -- задайтесь вопросом что человеку надо увидеть на рабочем графике? Числа (номера дней)? НЕТ! Так заем они занимают 90% пространства?

Человека интересует когда у него рабочий день, когда выходной. Если сменная работа то когда в какую смену. Если плавающий график, когда  во  сколько выходить на работу и до скольки работать.

НЕ ПУТАЙТЕ РАДИ БОГА С КАЛЕНДАРЕМ. государственный праздник он увидит сто раз в другом месте. Это не наша задача. Наша задача показать -- когда ему работать, когда у него выходной. Когда отпуск. Когда ему утвердили отгул.

**Comment by gsbelarus** [comment]
Почему бы не так? Сразу видно, когда рабочий день, когда выходной, во сколько начинать работу.

![drawing](https://cloud.githubusercontent.com/assets/5175764/9912460/71145220-5cb0-11e5-93da-56573e5f530d.png)

При выделении конкретного дня внизу открывается подробная информация. Например:

***28 января***

Первая смена. 8:00-13:00, 14:00-17:00.

**Comment by alexandra-gsoftware** [comment]
нормально

**Comment by YRozmysl** [comment]
интересный вариант

**Comment by arthur-latunov** [comment]
Вариант нарисованный выше, вполне неплох как прототип.
В эту тему:
1. Прямоугольная (может ближе к квадрату) разлиновка дней (ячейки).
2. Светлый фон, один, не надо мозаика фоном. Выделенный день чуть темнее, может окантовка темнее; сегодня полужирным.
3. Простые цвета цифр, - черные ПН-ПТ, темно-рыжий СБ, темно-красный ВС.
4. В ячейке достаточно места для разного: левый верхний угол число;  правый верхний закрасить небольшим треугольником или точкой:) (синий рабочий; зеленый отпуск; красный больничный; без заливки нерабочий; серый за свой счет и пр.), 4 цвета плюс без заливки достаточно, больше не запомнят:).
5. Правый нижний угол обозначение из справочника Тип отработанных часов поле Код (USR$CODE); левый нижний отработано часов (темно-серым). Но это уже к вопросу о табеле. Начало работы в правом нижнем углу мне тоже нравится.

Всё это только направление возможной реализации. Разработка таких своих элементов управления - дело очень серьезное. Возможно лучше вообще убрать календарь, но добавить вкладки График и Табель, а там построчно с разделителем нужные данные.

**Comment by gsbelarus** [comment]
1. Используем инвертирование для выделения клетки.
2. По выделенной клетке внизу выводим подробную информацию.
3. Если для клетки есть доп информация (кроме числа -- левый верхний угол, типа дня -- цвет фона, времени начала работы -- правый нижний угол), то рисуем цветной уголок. Можно предусмотреть цвет для гос праздника, смешанной смены (два разных участка) и т.п. Отдельный цвет можно использовать, когда несколько дополнительных событий.

![drawing](https://cloud.githubusercontent.com/assets/5175764/9934846/5b1744d0-5d5c-11e5-8690-dcae4a715034.png)
