### ISSUE TITLE
Цвет фона, а не точки

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#127]
Лучше использовать цвет фона дня при отображении календаря.

Например, как тут:

http://audama.com/images/opscenter370_screenshots/OpsCenter3_YearView.jpg

**Comment by alexandra-gsoftware** [comment]
в день может быть несколько событий, поэтому точки. Мне кажется, нужно, например подсвечивать гос. выходные, а жирным шрифтом(например) выделять дни, когда человек работает. Тогда наглядно видно, если он работает в воскресенье. Точки также оставить для любых остальных событий

**Comment by gsbelarus** [comment]
Не надо ничего выдумывать. Если этот человек работает в вс, то вс для него рабочий день. И не надо его показывать как выходной. То же и с праздниками.

**Comment by gsbelarus** [comment]
ЗАБУДЬТЕ ПРО ГУГЛ КАЛЕНДАРЬ, ПРО СБ ВС, ГОС ПРАЗДНИКИ.

ВАС ДОЛЖЕН ИНТЕРЕСОВАТЬ ***ТОЛЬКО*** ГРАФИК КОНКРЕТНОГО ЧЕЛОВЕКА.

ОН ДОЛЖЕН РАБОТАТЬ ПО ГРАФИКУ -- ЭТОТ ДЕНЬ РАБОЧИЙ. ДОЛЖЕН ОТДЫХАТЬ -- ЭТОТ ДЕНЬ ВЫХОДНОЙ.

Что тут непонятного??????????????????

**Comment by arthur-latunov** [comment]
1. Прямоугольная (может ближе к квадрату) разлиновка дней (ячейки).
2. Светлый фон, один, не надо мозаика фоном. Выделенный день чуть темнее, может окантовка темнее; сегодня полужирным.
3. Простые цвета цифр, - черные ПН-ПТ, темно-рыжий СБ, темно-красный ВС.
4. В ячейке достаточно места для разного: левый верхний угол число;  правый верхний закрасить небольшим треугольником или точкой:) (синий рабочий; зеленый отпуск; красный больничный; без заливки нерабочий; серый за свой счет и пр.), 4 цвета плюс без заливки достаточно, больше не запомнят:).
5. Правый нижний угол обозначение из справочника Тип отработанных часов поле Код (USR$CODE); левый нижний отработано часов (темно-серым). Но это уже к вопросу о табеле.

Всё это только направление возможной реализации. Разработка таких своих элементов управления - дело очень серьезное. Возможно лучше вообще убрать календарь, но добавить вкладки График и Табель, а там построчно с разделителем нужные данные.

**Comment by gsbelarus** [comment]
см. https://github.com/GoldenSoftwareLtd/GedeminSalary/issues/126
