### ISSUE TITLE
Время начала и окончания работы

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#128]
У нас на графике нигде не отображается время начала и окончания работы.

Есть позиции на предприятии, где это время постоянно может меняться. Например, в макдональдсе совершенно плавающие графики, где человек пять дней в неделю может выходить и каждый день в разное время. Кассиры в магазине. С 8:00 несколько, потом больше, в час пик еще больше.

**Comment by alexandra-gsoftware** [comment]
если такие данные есть в базе предприятия, то они попадают в мобильное приложение.

**Comment by YRozmysl** [comment]
Еще раз. Есть 2 вида календарных графика по сотруднику, 
1. Этот тот который привязывается к сотруднику в приказах. Там есть и начало и конец, хоть и перерывы на перекур и прочее можно вносить.
2.Есть "Календарный график" - это точная копия "Табеля мастера" там время начала и окончания работы привязано к номеру смены,которая там же и проставляется.
Надо только все это вытащить и обработать в приложении.

**Comment by YRozmysl** [comment]
Мы уже полезли в какие-то дебри.

**Comment by alexandra-gsoftware** [comment]
В графиках ставят или номер смены, или кол-во часов. Если стоит номер смены, то значит они ведут справочник смен по подразделениям и должностям (см вмк). У нас реализованы оба варианта в синхронизации с мобильным, тч вопрос только с красивым отображением

**Comment by YRozmysl** [comment]
В нашем стандартном (последней версии) ПИ, в Календарном графике, который клон ТМ, можно проставить и часы и номер смены. Тот вариант, когда можно было, либо часы, либо смена. Была первая версия графика.

**Comment by alexandra-gsoftware** [comment]
а если в смене несколько периодов времени, например, 9.00-12.00 и 13.00-18.00, надо их показывать?

**Comment by YRozmysl** [comment]
Если такое есть - это показывается, что перерыв на обед, надо брать крайние значение.

**Comment by alexandra-gsoftware** [comment]
нет, я про то, надо ли показывать в детализации этот перерыв? Например, эту смену можно показать как
09:00-18:00
или
09:00-12:00
13:00-18:00

**Comment by YRozmysl** [comment]
Нет, я считаю, что эти разрывы не нужны. Достаточно просто 09:00-18:00

**Comment by gsbelarus** [comment]
см. https://github.com/GoldenSoftwareLtd/GedeminSalary/issues/126

**Comment by alexandra-gsoftware** [comment]
сделаны для стандартных графиков. В календарных их не используют.
