### ISSUE TITLE
Отчество есть только в странах бывш СССР

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#129]
Иностранец нашей программой не сможет воспользоваться.

**Comment by AliakseiDanilchyk** [comment]
В Эфиопии есть отчество, но нет фамилии https://ru.wikipedia.org/wiki/%D0%A5%D0%B0%D0%B1%D0%B5%D1%88%D1%81%D0%BA%D0%BE%D0%B5_%D0%B8%D0%BC%D1%8F
