### ISSUE TITLE
Показывать дни и часы для начислений

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#136]
Для всех начислений (включая оклад), которые зависят от отработанного времени, показывать количество дней и часов, использованных в расчете.

**Comment by YRozmysl** [comment]
можно все проще. По всем видам начислений выводить часы и дни,если они есть в журнале исчисления по табелю USR$DOW, USR$HOW , если их нет, то ничего по дням и часам не выводить.
