### ISSUE TITLE
Несколько окладов

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#138]
Могут присутствовать в детальном списке, если человек заменял кого-то в течение месяца на других должностях и/или участках.

**Comment by alexandra-gsoftware** [comment]
Если у человека несколько одинаковых видов начислений на один месяц зачисления, они суммируются. Если у них разные месяцы зачисления, то они отображаются отдельно с указанием месяца и года зачисления.
