### ISSUE TITLE
График + табель

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#141]
Сейчас у нас сделан график работы. Это информация о том, как человек должен работать. какие дни рабочие, во сколько начало работы и т.п.

Табель -- это информация о том, как он фактически работал. На основе табеля делается расчет заработной платы.

Предложение выводить все на одном экране, который переименовать в ***График работы и табель***. Для тех дней, где есть в базе информация по табелю -- выводить табельные данные, для остальных -- информацию из графика. Не забываем, что график на предприятии. как правило, известен до конца года.

![drawing](https://cloud.githubusercontent.com/assets/5175764/9955136/52167e00-5df7-11e5-8bb8-428196c5baf1.png)

Все остальное как в issue про графие рабочего времени.

Какие типы дней по табелю бывают?

**Comment by YRozmysl** [comment]
типов  бывает неограниченно количество - это раз. А во вторых, нельзя  все грузить в одно. табель должен быть отдельно. рабочий календарь  тоже отдельно.

**Comment by alexandra-gsoftware** [comment]
согласна с Юрием. Возможно, лучше показывать в детализации табеля график? Или какой-нить режим Несовпадение с графиком

**Comment by gsbelarus** [comment]
зачем? просто сделаем две команды в меню ***График работы*** и ***Табель***

**Comment by alexandra-gsoftware** [comment]
режим сравнения - чтобы человек знал, когда и сколько он пропустил / переработал

**Comment by gsbelarus** [comment]
это будет усложнение. пока не надо.

**Comment by alexandra-gsoftware** [comment]
так табель тоже на следующую версию же?

**Comment by gsbelarus** [comment]
нет. без табеля это будет слишком ущербное приложение. надо делать сейчас

**Comment by alexandra-gsoftware** [comment]
итого, типы часов, которые выделяются цветами (в графике и табеле):
- рабочий день (код 0)
- ночные часы (1)
- нерабочий день (код 3)
- отпуск (4)
 - больничный (5)
- прогул (6)

Больничный, отпуск, прогул, ночные - стандартные типы часов.
Рабочий день - любой другой день с птичкой "рабочий" (например, командировка)
Нерабочий день - любой другой без птички "рабочий".

По поводу раскраски клетки. 
Если в день несколько типов событий с разным кодом, то цвета будут 
а) Рабочего дня (если было хоть одно рабочее событие)
б) Нерабочего дня (нет ни одного рабочего события).

Если в день одно событие, то используем его цвет.

Вопрос: кто-нибудь хочет выделить еще какие-то типы часов цветом?

**Comment by gsbelarus** [comment]
госпраздник какой нибудь пиктограммкой
