### ISSUE TITLE
Переименовать "Сообщения" в "Заявления"

### ISSUE THREAD

**Issue by YRozmysl** [GoldenSoftwareLtd/GedeminSalary#146]
Нужно переименовать так, как не совсем понятно, что подразумевает это "сообщение" в контексте ЗПиОК. Поэтому лучше всего его переименовать в "Запросы", что будет ближе к тематике (запрос на предоставление отгула, отпуска, справки и т.д)

**Comment by gsbelarus** [comment]
Запрос или Заявление? Надо чтобы называлось строго как называется соответствующая бумага, которую ручкой пишет человек, когда ему надо отгул.

**Comment by YRozmysl** [comment]
Тогда лучше заявление

**Comment by sywka** [comment]
В "Сообщениях" отображаются не только запросы, но и ответы на них, а так же служебные и информационные сообщения. Этому экрану скорее подойдет название "Почта". Про возможность отправки заявок написано на стартовом экране, который появляется при первом запуске приложения. Это все к тому, что возможно не стоит ничего менять, либо как-то по другому показать пользователю с какого экрана отправляются запросы.

**Comment by gsbelarus** [comment]
Это программисту понятно Почта, Сообщения. А человек всю жизнь писал от руки Заявление.
