### ISSUE TITLE
Trying to set non-nullable field timesheetkey to null

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#149]
Сейчас кидает при загрузке данных с сервера.

**Comment by alexandra-gsoftware** [comment]
а кто-то что-то ставил? на нашей бд ничего не менялось, всё делается на отдельной базе

**Comment by gsbelarus** [comment]
это в прил кидает ошибку. база гмк. все как и раньше. это новая версия прил и в ней ош.

**Comment by alexandra-gsoftware** [comment]
всё ясно. в Таблице DayEvent новое поле не должно быть нот нулл или должно иметь значение по умолчанию (то же самое со ссылкой на график, снять ограничение на нулл или добавить значение по умолчанию)

**Comment by gsbelarus** [comment]
и не просто добавить, а присвоить.
