### ISSUE TITLE
Ошибка при смене валюты

### ISSUE THREAD

**Issue by gsbelarus** [GoldenSoftwareLtd/GedeminSalary#159]

**Comment by sywka** [comment]
Крэш приложения или сообщение об ошибке загрузки? Из какой сети происходила синхронизация валют? Если из рабочей сети в офисе, то скорее всего запрос к сайту http://www.nbrb.by был перенаправлен на http://gsbelarus.com.

**Comment by alexandra-gsoftware** [comment]
сообщение об ошибке, не крэш
